ASPCoreFirstApp/Controllers/CustomerController.cs
using ASPCoreFirstApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASPCoreFirstApp.Controllers
{
    public class CustomerController : Controller
    {
        List<CustomerModel> customers = new List<CustomerModel>();
        public CustomerController()
        {
            customers.Add(new CustomerModel(0, "Don", 42));
            customers.Add(new CustomerModel(1, "Melvin", 18));
            customers.Add(new CustomerModel(2, "Jerry", 25));
            customers.Add(new CustomerModel(3, "Velma", 45));
            customers.Add(new CustomerModel(4, "Wendy", 33));
            customers.Add(new CustomerModel(5, "Kim", 90));

        }

        public IActionResult Index()
        {
            return View(customers);
        }
        public IActionResult ShowOnePerson(int Id)
        {
            return PartialView(customers.FirstOrDefault(c => c.Id == Id));
        }
    }
}

ASPCoreFirstApp/Views/Customer/Index.cshtml
@model IEnumerable<ASPCoreFirstApp.Models.CustomerModel>

<style>
    ul{
        list-style-type:none;
    }
    #customerInformationArea{
        border:1px solid black;
        border-radius: 5px;
        margin:10px;
        padding:10px;
    }
</style>
<p>Current time: @DateTime.Now</p>
<form  asp-action="ShowOnePerson" asp-controller="Customer">
    <ul>
        @foreach (var item in Model)
            {
                <li>
                    <input class="customerRadio" type="radio" name="Id" id="Id" value="@item.Id"/>
                    <label>@item.Name</label>
                </li>
            }

        </ul>
    <input type="submit" id="selectCustomer" />

</form>
<div id="customerInformationArea">
    <p>Display customer information here</p>
</div>

ASPCoreFirstApp/Views/Customer/ShowOnePerson.cshtml
@model ASPCoreFirstApp.Models.CustomerModel

<p>Current time: @DateTime.Now</p>
<div>
    <h4>CustomerModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>